# Generated by Django 5.1 on 2024-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BRA', 'Brasileira'), ('USA', 'Americana'), ('FRA', 'Francesa'), ('ITA', 'Italiana'), ('JPN', 'Japonesa'), ('KOR', 'Coreana'), ('CHN', 'Chinesa'), ('IND', 'Indiana'), ('RUS', 'Russa'), ('AUS', 'Australiana'), ('CAN', 'Canadense'), ('MEX', 'Mexicana'), ('ARG', 'Argentina'), ('COL', 'Colombiana'), ('PER', 'Peruana'), ('VEN', 'Venezuelana'), ('CHL', 'Chilena'), ('URY', 'Uruguaia'), ('ESP', 'Espanhola'), ('POR', 'Portuguasa'), ('GBR', 'Britânica'), ('DEU', 'Alemã'), ('NLD', 'Holandesa'), ('BEL', 'Belga'), ('SWE', 'Sueca'), ('NOR', 'Norueguesa'), ('FIN', 'Finlandesa'), ('DNK', 'Dinamarquesa'), ('POL', 'Polonesa'), ('CZE', 'Tcheca'), ('HUN', 'Húngara'), ('TUR', 'Turca'), ('GRC', 'Grega'), ('EGY', 'Egípcia'), ('ZAF', 'Sul-africana'), ('NGA', 'Nigeriana'), ('KEN', 'Queniana'), ('ETH', 'Etíope'), ('MAR', 'Marroquina')], max_length=100, null=True)),
            ],
        ),
    ]
